# Default values for tbot.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
image:
  registry: "ghcr.io"
  repository: "lyalyukev"
  tag: "v1.0.4-fecdcb7"
  arch: "amd64"
  os: "linux"
  pullsecret: "ghcr-secret"
  option: ""
secret:
  name: "tbot"
  env: "TELE_TOKEN"
  key: "tele_token"
securityContext:
  privileged: true
