# Default values for tbot.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: ghcr.io/lyalyukev
  tag: v1.0.0-1c1ec8c
  arch: amd64

secret:
  name: "tbot"
  env: "TELE_TOKEN"
  key: "tele_token"
securityContext:
  privileged: true